use crate::types::{Address, Bloom, H256, U256};
use ethers::types::Log;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct Receipt {
    /// Transaction hash.
    pub tx_hash: H256,
    /// Transaction index in block.
    pub tx_index: usize,
    /// Block hash.
    pub block_hash: H256,
    /// Block number.
    pub block_number: u64,
    /// Address of the sender.
    pub from: Address,
    /// Address of the receiver. None when its a contract creation transaction.
    pub to: Option<Address>,
    /// Cumulative gas used within the block after this was executed.
    pub cumulative_gas_used: U256,
    /// Gas used by this transaction alone.
    pub gas_used: Option<U256>,
    /// Contract address created, or None if not a deployment.
    pub contract_address: Option<Address>,
    /// Logs generated by this transaction.
    pub logs: Vec<Log>,
    /// The post-transaction state root.
    pub state_root: Option<H256>,
    /// Status: 1 for success, 0 for failure.
    pub status: u8,
    /// The bloom filter for the logs of this transaction.
    pub logs_bloom: Bloom,
}
